name: ci-q2-qsip2
on:
    pull_request:
        branches: ["main"]
    push:
        branches: ["main"]
jobs:
    ci:
        uses: qiime2/distributions/.github/workflows/lib-community-ci.yaml@dev
        with:
            github-repo: q2-qsip2
            env-file-name: q2-qsip2-qiime2-amplicon-2026.1.yml
